# Generated by Django 5.0.4 on 2024-04-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="المادة")),
            ],
            options={
                "verbose_name": "المادة",
                "verbose_name_plural": "المادة",
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="السنه الدراسية"),
                ),
            ],
            options={
                "verbose_name": "السنة_الدراسية",
                "verbose_name_plural": "السنه_الدراسية",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="باب")),
                (
                    "Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "الباب",
                "verbose_name_plural": "الباب",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان الفيديو"),
                ),
                ("video", models.FileField(upload_to="videos/")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2550,
                        null=True,
                        verbose_name="وصف الفيديو ",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="رقم الدرس ")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elearning.unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "الدرس",
                "verbose_name_plural": "الدرس",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="elearning.year"
            ),
        ),
    ]
