# Generated by Django 5.0.6 on 2024-06-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "elearning",
            "0002_alter_lesson_id_alter_lesson_title_alter_subject_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", models.DateField(verbose_name="بداية الاشتراك")),
                ("to", models.DateField(verbose_name="نهاية الاشتراك")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مدة الاشتراك",
                "verbose_name_plural": "مدة الاشتراك",
            },
        ),
    ]
