# Generated by Django 5.0.6 on 2024-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_pdffiles_lesson_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'المحاضرة', 'verbose_name_plural': 'المحاضرة'},
        ),
        migrations.AddField(
            model_name='pdffiles',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.PositiveIntegerField(verbose_name='رقم المحاضرة  '),
        ),
    ]
