# Generated by Django 5.0.6 on 2024-11-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_alter_lesson_options_pdffiles_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
    ]
