# Generated by Django 5.0.6 on 2024-12-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_remove_lesson_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Lecture',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Subject',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.year')),
            ],
            options={
                'verbose_name': 'الكورس',
                'verbose_name_plural': 'الكورس',
            },
        ),
        migrations.AddField(
            model_name='userexpiry',
            name='courses',
            field=models.ManyToManyField(blank=True, to='elearning.course'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
