# Generated by Django 5.0.6 on 2024-12-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_rename_lesson_lecture_remove_unit_subject_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning.course'),
            preserve_default=False,
        ),
    ]
